---
#celestia variables
rpc_port: 26657
p2p_port: 26656
grpc_port: 50051
network: mocha
node_type: light
p2p_network: mocha
rpc_url: public-celestia-mocha4-consensus.numia.xyz
celestia_home: '/home/zeachain'
mocha_pops_one_seed: 'ee9f90974f85c59d3861fc7f7edb10894f6ac3c8@seed-mocha.pops.one:26656'