---
# # Enable if needed. Keys are deposed manually on server
# - name: copy identity key
#   copy:
#     src: files/validator-keypair.json
#     dest: "{{ solana_validator_dir }}/config/validator-keypair.json"
#   become: no

# - name: copy vote key
#   copy:
#     src: files/vote-account-keypair.json
#     dest: "{{ solana_validator_dir }}/config/vote-account-keypair.json"
#   become: no

- name: Template config file to server
  ansible.builtin.template:
    src: "templates/config-{{ network_type }}.toml.j2"
    dest: "{{ solana_validator_config_dir }}/config.toml"
  become: no

- name: Copy 'solana-exporter' docker compose file
  template:
    src: templates/exporter.docker-compose.yml.j2
    dest: "{{ solana_exporter_dir }}/exporter.docker-compose.yml"
