---
# Will be removed after clean up user ubuntu 1000
- set_fact:
    ansible_user: devops

- block:
    - ansible.builtin.include_tasks: solana_install.yml
    - ansible.builtin.include_tasks: copy_files.yml
    - ansible.builtin.include_tasks: service.yml
    - ansible.builtin.include_tasks: validator.yml
  when: deployment_type == 'install'

- ansible.builtin.include_tasks: solana_upgrade.yml
  when: deployment_type == 'upgrade'

- ansible.builtin.include_tasks: metrics.yml
  when: fetch_metrics | default(false)
