---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ non_root_user }}"
    group: "{{ non_root_group }}"
    mode: "0755"
  loop:
    - "{{ solana_validator_dir }}"
    - "{{ solana_validator_config_dir }}"
    - "{{ solana_validator_data_dir }}"
    - "{{ solana_validator_data_dir }}/ledger"
    - "{{ solana_validator_data_dir }}/accounts"
    - "{{ solana_exporter_dir }}"
    - "{{ solana_exporter_dir }}/data"
    - "{{ solana_exporter_dir }}/exporter"
  become: no

#Install required packages
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: install 'rust'
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  become: no

- name: Ensure rustup path is in PATH
  lineinfile:
    path: '~/.bashrc'
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    create: yes
  become: no

- name: Check if destination repo exists
  stat:
    path: "{{ solana_validator_build_dir }}"
  register: repo_stat

- name: Move existing repository if it exists
  shell: "mv {{ solana_validator_build_dir }} {{ solana_validator_build_dir }}-$(date +%Y%m%d%H%M%S)"
  when: repo_stat.stat.exists

- name: Clone Firedancer repository
  shell: 'git clone --recurse-submodules {{ solana_validator_build_url }} {{ solana_validator_build_dir }}'
  become: no

- name: Checkout version
  shell: 'git checkout {{ solana_version }}'
  args:
    chdir: "{{ solana_validator_build_dir }}"
  become: no

# Asks for 'sudo' pwd during execution, No issue for 'devops' user, can 'sudo' without pwd
- name: Run dependency installation script
  shell: 'export FD_AUTO_INSTALL_PACKAGES=1 && yes | ./deps.sh'
  args:
    chdir: "{{ solana_validator_build_dir }}"
  become: no

- name: Make 'fdctl' and 'solana' binaries
  shell: |
    export PATH="$HOME/.cargo/bin:$PATH"
    make -j fdctl solana || true
  args:
    chdir: "{{ solana_validator_build_dir }}"
  become: no

- name: Ensure Firedancer build path is in PATH
  lineinfile:
    path: '~/.bashrc'
    line: 'export PATH="$HOME/solana-validator/firedancer/build/native/gcc/bin:$PATH"'
    create: yes
  become: no
