---
- name: Set network endpoint
  shell:
    "{{ solana_validator_binary_path }}/solana config set --url https://api.{{ network_type }}.solana.com/"

- name: Set keypair
  shell:
    "{{ solana_validator_binary_path }}/solana config set --keypair {{ solana_validator_config_dir }}/validator-keypair.json"

# # Disable 'irdma' driver so that 'firedancer' starts correctly
# - name: Ensure irdma driver is disabled  
#   shell: rmmod irdma  
#   become: yes  

- name: Stop Solana validator service
  systemd:
    name: solana.service
    state: stopped
  become: yes
  failed_when: false


- name: Start and enable Solana validator service
  systemd:
    name: solana.service
    state: started
    enabled: yes
  become: yes

- name: Copy 'solana-exporter' docker compose file
  template:
    src: templates/exporter.docker-compose.yml.j2
    dest: "{{ solana_exporter_dir }}/exporter.docker-compose.yml"

- name: stop solana-exporter container if existing
  shell:
    "docker-compose -f {{ solana_exporter_dir }}/exporter.docker-compose.yml down"

- name: Start solana-exporter container
  shell:
    "docker-compose -f {{ solana_exporter_dir }}/exporter.docker-compose.yml up -d"
