#Collection Galaxy metadata Structure can be found here: https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: proviroll
name: ansible_collection
version: "1.0.0"
readme: README.md
description: Reusable Ansible roles and playbooks for blockchain and supporting infrastructure.
license_file: 'LICENSE'
repository: https://github.com/proviroll/ansible-collection
documentation: https://github.com/proviroll/ansible-collection
homepage: https://github.com/proviroll/ansible-collection
issues: https://github.com/proviroll/ansible-collection/issues
dependencies:
  "community.docker": ">=3.0.0,<4.0.0"
  "community.general": ">=6.0.0,<7.0.0"
  "ansible.posix": ">=1.0.0,<2.0.0"
authors:
  - Proviroll
build_ignore:
  - .github
