#!/bin/bash
exec agave-validator \
    --identity /home/devops/solana-validator/config/validator-keypair.json \
    --vote-account /home/devops/solana-validator/config/vote-account-keypair.json \
    --ledger /home/devops/solana-validator/data/ledger \
    --accounts /home/devops/solana-validator/data/accounts \
    --no-snapshot-fetch \
    --snapshots /home/devops/solana-validator/data \
    --maximum-full-snapshots-to-retain 1 \
    --maximum-incremental-snapshots-to-retain 2 \
    --log /home/devops/solana-validator/config/agave-validator.log \
    --private-rpc \
    --rpc-port 8899 \
    --rpc-bind-address 127.0.0.1 \
    --dynamic-port-range 8000-8020 \
    --only-known-rpc \
    --known-validator 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on \
    --known-validator Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN \
    --known-validator 9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv \
    --known-validator 7XSY3MrYnK8vq693Rju17bbPkCN3Z7KvvfvJx4kdrsSY \
    --entrypoint entrypoint2.testnet.solana.com:8001 \
    --entrypoint entrypoint3.testnet.solana.com:8001 \
    --entrypoint entrypoint.testnet.solana.com:8001 \
    --expected-genesis-hash 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY \
    --wal-recovery-mode skip_any_corrupted_record \
    --limit-ledger-size
