---
# Setup SSL certificates & renewals
- name: Install Certbot package
  ansible.builtin.package:
    name:
      - certbot
      - python3-certbot-dns-cloudflare
    state: present

- name: Create Cloudflare credentials file
  ansible.builtin.copy:
    dest: "{{ nginx_config_dir }}/cloudflare.ini"
    content: |
      dns_cloudflare_api_token = "{{ cloudflare_token }}"
    mode: "0600"

- name: Obtain SSL certificates
  ansible.builtin.command: >
    certbot certonly --non-interactive --agree-tos --dns-cloudflare --dns-cloudflare-credentials {{ nginx_config_dir }}/cloudflare.ini -d '{{ subdomain_template }},*.{{ subdomain_template }}' --non-interactive --agree-tos --email {{ cloudflare_email }} --expand

# Cron job for Certbot renewal
- name: Add Certbot renewal cron job with NGINX reload
  ansible.builtin.cron:
    name: "{{ certbot_renewal_cron_name }}"
    minute: "{{ certbot_renewal_cron_time.minute }}"
    hour: "{{ certbot_renewal_cron_time.hour }}"
    job: "{{ certbot_renewal_job }}"
    state: present
