---
# Configure NGINX
- name: Create data dir
  ansible.builtin.file:
    path: /home/evmos/nginx
    state: directory

- name: Template .conf file
  ansible.builtin.template:
    src: './templates/nginx.conf.j2'
    dest: /home/evmos/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Install passlib
  ansible.builtin.pip:
    name: passlib
    executable: pip3

- name: Add htpasswd
  ansible.builtin.htpasswd:
    path: /home/evmos/nginx/.htpasswd
    name: '{{ metrics_auth_user }}'
    password: '{{ metrics_auth_password }}'
