---
- name: Create data dir
  ansible.builtin.file:
    path: "{{ nginx_dir }}"
    state: directory

- name: Copy .conf file
  ansible.builtin.template:
    src: "{{ nginx_conf_file }}"
    dest: "{{ nginx_dir }}/nginx.conf"
  notify:
    - Reload nginx

# Requires `apache2-utils` to be installed.
# Currently done in roles/setup_machine/tasks/main.yml
# -b: Use password from arg, don't prompt
# -c: Create file if doesn't exist
# -v: Verify password. Correct exit 0, incorrect exit 3
- name: Validate NGINX htpasswd file
  ansible.builtin.command: htpasswd -b -v {{nginx_dir}}/.htpasswd {{metrics_auth_user}} {{metrics_auth_password}}
  ignore_errors: true
  changed_when: false
  register: validate_password_out
# Re-running htpasswd with the same password will result in a different file since the salt changes
- name: Create NGINX htpasswd file
  ansible.builtin.command: htpasswd -b -c {{nginx_dir}}/.htpasswd {{metrics_auth_user}} {{metrics_auth_password}}
  when: validate_password_out.rc != 0

- name: Start NGINX
  community.docker.docker_container:
    name: "{{ container_name_nginx }}"
    state: started
    image: nginx:alpine
    pull: true

    volumes:
      - "{{ nginx_dir }}:/etc/nginx"

    restart_policy: unless-stopped
    network_mode: host
    log_driver: json-file
    log_options:
      max-file: "10"
      max-size: 30m
      mode: non-blocking
      max-buffer-size: 4m
