---
# Set permissions
- name: Match user-group data folder permissions for docker container
  become: true
  ansible.builtin.file:
    path: "{{ host_data_dir }}"
    owner: "{{ evmos_user }}"
    group: "{{ evmos_group }}"
    recurse: true

- name: Match user-group config folder permissions for docker container
  become: true
  ansible.builtin.file:
    path: "{{ host_config_dir }}"
    owner: "{{ evmos_user }}"
    group: "{{ evmos_group }}"
    recurse: true

# Set up the systemd init service
- name: Ensure script is executable
  ansible.builtin.file:
    path: "{{ host_config_dir }}/init.sh"
    mode: "0755"

- name: Template systemd service file for script
  ansible.builtin.template:
    src: templates/init.service.j2
    dest: /etc/systemd/system/evmos-init-script.service

- name: Reload systemd to make it aware of the new service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start the service
  ansible.builtin.systemd:
    name: evmos-init-script
    state: started
