---
- name: Gracefully Stop the lotus Docker Container
  community.docker.docker_container:
    name: "{{ lotus_container_name }}"
    state: absent
  when: fresh_sync | bool

- name: Remove unused Docker volumes
  community.docker.docker_prune:
    volumes: yes
  when: fresh_sync | bool

- name: Delete data and config dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ lotus_data_dir }}"
    - "{{ lotus_config_volume }}"
    - "{{ lotus_snapshot_location }}"
  when: fresh_sync | bool

- name: Create config and data dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ lotus_config_volume }}"
    - "{{ lotus_snapshot_location }}"

- name: Increase net.core.rmem_max
  ansible.builtin.sysctl:
    name: net.core.rmem_max
    value: '2500000'
    state: present
    reload: yes

- name: Increase net.core.wmem_max
  ansible.builtin.sysctl:
    name: net.core.wmem_max
    value: '2500000'
    state: present
    reload: yes

- name: Increase net.core.wmem_max
  ansible.builtin.sysctl:
    name: net.core.rmem_default
    value: '2500000'
    state: present
    reload: yes

- name: Make sysctl changes permanent
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item.line }}"
    create: yes
  with_items:
    - { line: 'net.core.rmem_max=2500000' }
    - { line: 'net.core.wmem_max=2500000' }
    - { line: 'net.core.rmem_default=2500000' }

- name: Template lotus full node config file
  ansible.builtin.template:
    src: "templates/config.toml.j2"
    dest: "{{ lotus_config_volume }}/{{ lotus_config_filename }}"

- name: Modify permissions to match user-group inside docker image
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    recurse: true
    mode: "0700"
  with_items:
    - "{{ lotus_data_dir }}"
    - "{{ lotus_config_volume }}"
    - "{{ lotus_snapshot_location }}"

- name: Ensure aria2 is Installed
  ansible.builtin.apt:
    name:
      - aria2
      - ntp
    state: present
  become: true

- name: Ensure NTP is running
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true

## TODO improve snapshot download logic. 
- name: Download Snapshot
  become: true
  ansible.builtin.shell: |
    aria2c -x5 "{{ lotus_calibnet_snapshot_url }}" -o snapshot.forest.car.zst
  args:
    chdir: "{{ lotus_snapshot_location }}"
    executable: /bin/bash
  when: fresh_sync | bool

- name: Start lotus node container
  register: lotus_docker_start
  community.docker.docker_container:
    name: "{{ lotus_container_name }}"
    state: started
    image: "{{ filecoin_dockerhub_imagename }}:{{ filecoin_dockerhub_tag }}"
    pull: true
    stop_timeout: 20
    #TODO add genesis file if necessary --genesis="{{ lotus_path }}/genesis.car"
    command: "{{ lotus_container_args }}"
    volumes:
      - "{{ lotus_config_volume }}/{{ lotus_config_filename }}:{{ lotus_path }}/{{ lotus_config_filename }}"
      - "{{ lotus_data_dir }}:{{ lotus_path }}"
      #- "{{ execution_engine_jwtsecret_dirpath }}:{{ lotus_jwtsecret_dirpath_from_process }}"
    restart_policy: always
    network_mode: host
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options }}"
    memory_swappiness: 0
    labels:
      promtail_logging: "true"
      scrape_location: "lotus"
      instance: "{{ inventory_hostname }}"
      network: "{{ hostvars[inventory_hostname]['network'] }}"
