---
solana_version: "v2.0.24"
solana_api_url: https://api.testnet.solana.com/

non_root_user: "1000"
non_root_group: "1000"

max_map_count: 1000000
descriptor_nofile: 1000000
solana_binary_path: /bin:/usr/bin:/home/devops/.local/share/solana/install/active_release/bin

solana_port_range: "8000:8020"

vote_account_pubkey: 8GG4mTYhjfoHsHUwvLdQzYjEkXVLxGDv1DPPkyWAJS54
