---
- hosts: all
  become: true
  vars_files:
    - "../../vault.yml"
  vars:
    metrics_apps:
      - name: nodeexporter
        port: "{{ nodeexporter_port }}"
        public_port: "{{ nodeexporter_public_port }}"
        host: "127.0.0.1"
  roles:
    - node_exporter
    - monitoring_target_nginx
