---
- name: Setup server
  hosts: monitoring-1
  become: true
  roles:
    - bootstrap
    - install_packages

- name: Deploy monitoring
  hosts: monitoring-1
  become: true
  # gather_facts:
  vars_files:
  - ../../vault.yml
  vars:
    grafana_docker_data_dir: /var/lib/grafana
    metrics_apps:
      - name: nodeexporter
        port: "{{ nodeexporter_port }}"
        public_port: "{{ nodeexporter_public_port }}"
        host: "127.0.0.1"
  roles:
    - prometheus
    - grafana
    - alertmanager
    - node_exporter
    - monitoring_nginx
    - firewall
   