---
- hosts: monitoring-1
  become: true
  vars:
    grafana_docker_data_dir: /var/lib/grafana
    prometheus_endpoint: http://{{ monitoring_server_address }}:9090/
  vars_files:
    - "../../vault.yml"
  gather_facts: false
  roles:
    - grafana