---
- name: Create docker volume alertmanager-data
  community.docker.docker_volume:
    name: alertmanager-data

- name: Create alertmanager_config_dir
  ansible.builtin.file:
    path: "{{ alertmanager_config_dir }}"
    state: directory

- name: Copy alertmanager config
  ansible.builtin.template:
    src: ./templates/alertmanager.yml
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
  notify:
    - reload alertmanager

- name: Start alertmanager
  community.docker.docker_container:
    name: "{{ container_name_alertmanager }}"
    state: started
    image: prom/alertmanager
    pull: true

    command: >
      --config.file=/config/alertmanager.yml --web.listen-address=":{{ alertmanager_web_port }}"

    volumes:
      - "{{ alertmanager_config_dir }}:/config"
      - alertmanager-data:/data

    restart_policy: unless-stopped
    network_mode: host
    log_driver: json-file
    log_options:
      max-file: "10"
      max-size: 30m
      mode: non-blocking
      max-buffer-size: 4m
