---
- name: Copy alertmanager config
  ansible.builtin.template:
    src: "./templates/{{ alertmanager_config_file }}"
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
  notify:
    - reload alertmanager
