---
- name: install ufw
  apt:
    name: ufw
    state: present
  become: yes

- name: Allow SSH port
  community.general.ufw:
    rule: allow
    port: 22
    comment: "ssh"

- name: Open validator ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    comment: "{{ item.name }}"
    proto: "{{ item.proto | default('tcp') }}"
  loop: "{{ firewall_ports | default([]) }}"

# Warning: The task has condition "And lenght > 0", without it, and empty 'public_port' variable will result in 'Allow any to any'
- name: Open public metrics ports (if public port is specified)
  community.general.ufw:
    rule: allow
    port: "{{ item.public_port }}"
    comment: "{{ item.name }}"
    proto: "{{ item.proto | default('tcp') }}"
  loop: "{{ metrics_apps | default([]) }}"
  when: item.public_port is defined and item.public_port | string | length > 0

- name: Block private metrics ports
  ansible.builtin.ufw:
    rule: deny
    port: "{{ item.port }}"
    proto: any
  loop: "{{ metrics_apps | default([]) }}"

- name: Allow source-restricted ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
    from_ip: "{{ item.from_ip }}"
    comment: "{{ item.name }}"
  loop: "{{ firewall_source_ports | default([]) }}"

- name: Enable firewall
  community.general.ufw:
    state: enabled
    default: deny
