- name: Run Celestia App container
  docker_container:
    name: celestia-app
    image: ghcr.io/celestiaorg/celestia-app:9523b4c  # Use specified Docker image
    state: started
    user: "0:0"
    ports:
      - "{{ rpc_port }}:{{ rpc_port }}"    # RPC Port
      - "{{ p2p_port }}:{{ p2p_port }}"    # P2P Port
      - "{{ grpc_port }}:{{ grpc_port }}"  # gRPC Port
    env:
      SEEDS: "ee9f90974f85c59d3861fc7f7edb10894f6ac3c8@seed-mocha.pops.one:26656"  # Adding seed directly
      MAX_NUM_PEERS: "2"
    volumes:
      - "{{ ansible_env.HOME }}/celestia-app:/app/celestia"  # Mount directory inside container at /app/celestia
    restart_policy: always
    