- name: Configur swap memory
  hosts: all
  vars:
    swap_file_path: /swapfile
    swap_file_size_mb: '65536'  # 64GB
    swap_swappiness: '60'
    swap_file_state: present # present/absent to Creates/Remove swap file
  become: true
  roles:
    - configure_swap

- name: System setup
  hosts: all
  become: true
  vars_files:
    - "../../vault.yml"
  vars:
    metrics_apps:
      - name: nodeexporter
        port: "{{ nodeexporter_port }}"
        public_port: "{{ nodeexporter_public_port }}"
        host: "127.0.0.1"
      - name: validator
        port: 7999
        public_port: 37999
        host: "127.0.0.1"
      - name: solana_exporter
        port: 9999
        public_port: 39999
        host: "127.0.0.1"
  roles:
    - monitoring_target_nginx

- name: Deploy solana validator
  hosts: all
  become: true
  vars:
    network: solana
    network_type: testnet # Values : testnet, devnet, mainnet-beta
    chain_id: 
  roles:
    - solana_firedancer