---
- name: Upgrade solana firedancer validator
  hosts: all
  become: true
  vars:
    network: solana
    solana_previous_version : "v0.703.20300"
    solana_version: "v0.707.20306" # Must be updated on 'solana_firedancer' role as well
    deployment_type: upgrade
    network_type: testnet # Values : testnet, devnet, mainnet-beta
  roles:
    - solana_firedancer
