- name: Checking required variables
  fail: msg="Variable '{{ item }}' is not defined"
  when: vars[item] is not defined
  with_items: "{{ required_vars }}"

- name: Deploy and start lotus fountain container
  community.docker.docker_container:
    name: "{{ container_name_fountain }}"
    state: started
    image: "{{ fountain_image_and_tag }}"
    pull: true
    stop_timeout: 20
    command: "{{ fountain_args }}"
    restart_policy: always
    network_mode: host
    volumes:
      - "{{lotus_host_data_dir}}:{{lotus_container_data_dir}}"
    env:
      LOTUS_PATH: "{{ lotus_container_data_dir }}"
      RECAPTCHA_SECRET_KEY: "{{ lotus_fountain_recaptcha_secret_key }}"
      RECAPTCHA_SITE_KEY: "{{ lotus_fountain_recaptcha_site_key }}"
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options }}"
    detach: yes
    labels:
      promtail_logging: "true"
      scrape_location: "faucet"
      instance: "{{ inventory_hostname }}"
      network: "{{ hostvars[inventory_hostname]['network'] }}"


- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx_host_data_dir }}"

- name: Copy Nginx configuration template
  template:
    src: templates/nginx-faucet.conf.j2
    dest: "{{ nginx_host_data_dir }}/nginx.conf"
  notify:
      - Restart Nginx

- name: Run Nginx container
  docker_container:
    name: "nginx-{{ container_name_fountain }}"
    image: nginx
    volumes:
      - "{{ nginx_host_data_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
    network_mode: host
    detach: yes
  notify:
      - Restart Nginx

