container_name_fountain: lotus-fountain
fountain_image_and_tag: filecoin/lotus-all-in-one:stable-calibnet
lotus_host_data_dir: /data/lotus_data
lotus_container_data_dir: /var/lib/lotus
nginx_host_data_dir: /home/{{ansible_user}}/nginx-{{container_name_fountain}}/
fountain_args: "lotus-fountain run --front '0.0.0.0:7777' --amount {{ lotus_fountain_amount }} --data-cap {{data_cap_value}}"
faucet_port: "7777"
lotus_rpc_port: "1234"
lotus_fountain_amount: 100
data_cap_value: 1048576
docker_log_driver: json-file
# Limit local size to 500MB of logs per container
docker_log_options:
  max-file: "5"
  max-size: 100m
