{
 "title": "Cosmos Nodes",
 "tags": [ "testnet" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "ChainID",
    "query": {
     "query": "label_values(cometbft_consensus_state_syncing,chain_id)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(cometbft_consensus_state_syncing{chain_id=\"$chain_id\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cometbft_consensus_state_syncing{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cometbft_consensus_total_txs{pod=\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(cometbft_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", pod=\"$pod\"}[$__range])/rate(cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", pod=\"$pod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cometbft_mempool_size{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cometbft_consensus_missing_validators{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_mempool_recheck_times{chain_id=\"$chain_id\", pod=\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_mempool_failed_txs{chain_id=\"$chain_id\", pod=\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cometbft_p2p_peers{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cometbft_consensus_validators_power{pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feemarket Base Fee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feemarket_base_fee{pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "state-timeline",
   "description": "Time between BeginBlock and EndBlock in ms",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(cometbft_state_block_processing_time_bucket{chain_id=\"$chain_id\", pod=\"$pod\"}[5m]))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Consensus Block Interval",
   "type": "state-timeline",
   "description": "Time between this and the last block",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(cometbft_consensus_block_interval_seconds_bucket{chain_id=\"$chain_id\", pod=\"$pod\"}[5m]))",
     "legendFormat": "sec"
    }
   ]
  },
  {
   "title": "Freemarket Block Gas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feemarket_block_gas{pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store#Get Calls",
   "type": "stat",
   "description": "Duration of an IAVL Store#Get call",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(store_iavl_get{quantile=\"0.5\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(store_iavl_get{quantile=\"0.9\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(store_iavl_get{quantile=\"0.99\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Store#Commit Calls",
   "type": "stat",
   "description": "Duration of an IAVL Store#Commit call",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(store_iavl_commit{quantile=\"0.5\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(store_iavl_commit{quantile=\"0.9\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(store_iavl_commit{quantile=\"0.99\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Store#Delete Calls",
   "type": "stat",
   "description": "Duration of an IAVL Store#Delete call",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(store_iavl_delete{quantile=\"0.5\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(store_iavl_delete{quantile=\"0.9\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(store_iavl_delete{quantile=\"0.99\", pod=\"$pod\"}) by (pod, quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cometbft_consensus_num_txs{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cometbft_mempool_size{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Mempool Size"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Round",
   "type": "graph",
   "description": "cometbft_consensus_rounds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cometbft_consensus_rounds{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Round"
    }
   ]
  },
  {
   "title": "$chain_id validators overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true
  },
  {
   "title": "Voting Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cometbft_consensus_validators_power{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Online"
    },
    {
     "expr": "sum(cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(cometbft_consensus_byzantine_validators_power{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(cometbft_consensus_validators{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(cometbft_consensus_missing_validators{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(cometbft_consensus_byzantine_validators{chain_id=\"$chain_id\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Validators with missing blocks",
   "type": "stat",
   "description": "Number of validators missing blocks",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{chain_id=\"$chain_id\", pod=\"$pod\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Highest missed blocks",
   "type": "stat",
   "description": "Number of highest missed blocks for validators on chain",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validators_missed_blocks{chain_id=\"$chain_id\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Top validators with missed blocks",
   "type": "table",
   "description": "Top validators with missed blocks",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0))"
    }
   ]
  },
  { "title": "Node stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"evmos-storage-${pod}\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"evmos-storage-${pod}\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"evmos-storage-${pod}\"})\n* 100)\n"
    }
   ]
  },
  {
   "title": "Data grows (24h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"evmos-storage-${pod}\"}) - sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"evmos-storage-${pod}\"} offset 24h)) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=\"$pod\"}[4h:1m])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=\"$pod\"}[4h:1m])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}