{
 "title": "Fuel",
 "description": "Internet of blockchains",
 "tags": [
  "Blockchain",
  "Cosmos"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": {
     "query": "label_values({__name__=~\"(tendermint|cometbft)_consensus_height\"}, group)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values({__name__=~\"(tendermint|cometbft)_consensus_height\", group=\"$group\"},network)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values({__name__=~\"(tendermint|cometbft)_consensus_height\", group=\"$group\", network=\"$network\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$group overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_total_txs\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_height\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Active valdiators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_active{group=\"$group\", network=\"$network\", node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_height\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{group=\"$group\", network=\"$network\", node=\"$node\"}[5m]) \n/ \nrate(cometbft_consensus_block_interval_seconds_count{group=\"$group\", network=\"$network\", node=\"$node\"}[5m])"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_validators_power\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_validators\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_missing_validators\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_byzantine_validators\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_validators_power\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_missing_validators_power\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_byzantine_validators_power\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_block_size_bytes\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_consensus_num_txs\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Is Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_active{group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Is Syncing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_active{group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_p2p_peers\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Validator Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_rank{group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_mempool_size\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_mempool_failed_txs\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_mempool_recheck_times\", group=\"$group\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_p2p_peer_receive_bytes_total\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"(tendermint|cometbft)_p2p_peer_send_bytes_total\", group=\"$group\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}