{
 "title": "namada-validators",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values({job=\"$job\", network=\"$network\"},node)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values({job=\"namada\"},job)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values({job=\"$job\"},network)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator set",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(1, namada_network_max_set_size)",
     "legendFormat": "max_set"
    },
    {
     "expr": "topk(1, namada_network_active_set_size)",
     "legendFormat": "active_set"
    }
   ]
  },
  {
   "title": "Network epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(1, namada_network_epoch)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lowest stake in network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "NAM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, namada_network_lowest_active_set_stake)",
     "legendFormat": "lowest stake in network"
    }
   ]
  },
  {
   "title": "Stake threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "NAM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, namada_network_stake_threshold)",
     "legendFormat": "threshold"
    }
   ]
  },
  { "title": "VALIDATOR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_uptime_percentage{node=\"$node\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "NODE SYNC?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_node_catch_up{node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{node=\"$node\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Missed blocks in window",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_missed_blocks{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active set rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_active_set_rank{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Comission",
   "type": "stat",
   "description": "Bonded Tokens for the monitored validator",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_commission{node=\"$node\"} * 100",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Validator state (All states monitored)",
   "type": "stat",
   "description": "Possible values (mapped) :\n1 - Active consensus (Ok)\n2 - Active below capacity\n3 - Active below threshold\n4 - Jailed\n5 - Inactive\n0 - UNKNOWN",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_state{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest block from validator RPC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_node_latest_block{node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator bond",
   "type": "stat",
   "description": "Bonded Tokens for the monitored validator",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "NAM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_total_bonds{node=\"$node\"} / 1000000",
     "legendFormat": "uptime"
    }
   ]
  }
 ]
}