{
 "title": "Solana Firedancer Validator",
 "description": "Solana Validator Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info, job)"
   },
   { "name": "network", "query": { "query": "label_values(network)" } },
   { "name": "node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Solana verison",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_version{job=\"$job\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_confirmed_epoch_number{job=\"$job\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Is active",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "solana_active_validators{job=\"$job\",network=\"$network\", node=\"$node\", state=\"current\"}"
    }
   ]
  },
  {
   "title": "Is delinquent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_validator_delinquent{}" }
   ]
  },
  {
   "title": "Validator last vote",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_last_vote{job=\"$job\",network=\"$network\", node=\"$node\", nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\"}"
    }
   ]
  },
  {
   "title": "My Credits",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_activated_stake{job=\"$job\", network=\"$network\", node=\"$node\"} / 1000000000",
     "legendFormat": "credits"
    }
   ]
  },
  {
   "title": "Leaderslots this epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_leaderSlots" }
   ]
  },
  {
   "title": "Active stake",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_activated_stake{job=\"$job\", network=\"$network\", node=\"$node\"} / 1000000000"
    }
   ]
  },
  {
   "title": "Validator produced blocks (When it's producing)",
   "type": "stat",
   "description": "Producing blocks is rotative between validators each X slots (4 slots usually). The schedule of blocks producing is distributes by the leader of Epoch. When the validator has no blocks scheduled to produce, and is doing other duties (voting), this metric has no data.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "solana_leader_slots_total{nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\",status=\"valid\"}"
    }
   ]
  },
  {
   "title": "Total Validator skipped blocks (When it's procuding)",
   "type": "stat",
   "description": "Producing blocks is rotative between validators each X slots (4 slots usually). The schedule of blocks producing is distributes by the leader of Epoch. When the validator has no blocks scheduled to produce, and is doing other duties (voting), this metric has no data.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_leader_slots_total{nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\",status=\"skipped\"}"
    }
   ]
  },
  {
   "title": "Recent validator skipped blocks (When it's producing)",
   "type": "stat",
   "description": "Producing blocks is rotative between validators each X slots (4 slots usually). The schedule of blocks producing is distributes by the leader of Epoch. When the validator has no blocks scheduled to produce, and is doing other duties (voting), this metric has no data.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(solana_leader_slots_total{nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\",status=\"skipped\"} [10m])"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_nodes" }
   ]
  },
  {
   "title": "Skip rate - testing accuracy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum({app=\"solana-exporter\", job=\"solana\", status=\"skipped\", nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\"}) \n/ (sum({app=\"solana-exporter\", job=\"solana\", status=\"valid\", nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\"}) \n+ sum({app=\"solana-exporter\", job=\"solana\", status=\"skipped\", nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\"}))",
     "legendFormat": "My skip rate"
    },
    { "expr": "sol_pctTotSkipped", "legendFormat": "Cluster skip rate" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU used"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "RAM used "
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=~\"$job\"} / node_memory_SwapTotal_bytes{job=~\"$job\"})) * 100",
     "legendFormat": "SWAP used "
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk used"
    }
   ]
  }
 ]
}