{
 "title": "Solana Agave validator",
 "description": "Solana Validator Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(solana_node_version,network)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(solana_node_version{network=\"$network\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validator last vote",
   "type": "stat",
   "description": "Last vote of the validator",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_last_vote{job=\"$job\",network=\"$network\", node=\"$node\", nodekey=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster last vote",
   "type": "stat",
   "description": "Last vote in the cluster / network",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_cluster_last_vote{job=\"solana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_pctEpochElapsed" }
   ]
  },
  {
   "title": "MIssed slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_skippedSlots" }
   ]
  },
  {
   "title": "Skip rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_pctSkipped" }
   ]
  },
  {
   "title": "Vote account balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{job=\"$job\", network=\"$network\", node=\"$node\", address=\"2paKzeZKpPpSd5kJdoNZ9LTWhHMJXDL3bjMhfRa7xjus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity account balance (fees payer)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{job=\"$job\", network=\"$network\", node=\"$node\", address=\"EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node blockheight",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_block_height{job=\"solana\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator RPC endpoint is up",
   "type": "stat",
   "description": "Is the node's RPC endpoint Active",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"solana\", network=\"$network\", node=\"$node\", instance=~\".+:9999\"}"
    }
   ]
  },
  {
   "title": "Is healthy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_is_healthy{job=\"solana\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Is delinquent (should not be)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_delinquent{job=\"solana\", network=\"$network\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active stake",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_active_stake{job=\"solana\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_epoch_number{job=\"solana\", network=\"$network\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Cluster validators - Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_cluster_validator_count{job=\"solana\", network=\"$network\", node=\"$node\",state=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster validators - Delinquent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_cluster_validator_count{job=\"solana\", network=\"$network\", node=\"$node\",state=\"delinquent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_nodes" }
   ]
  },
  {
   "title": "My Credits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sol_validatorCreditsCurrent", "legendFormat": "credits" }
   ]
  },
  {
   "title": "Skip rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sol_pctSkipped", "legendFormat": "My skip rate" },
    { "expr": "sol_pctTotSkipped", "legendFormat": "Cluster skip rate" }
   ]
  }
 ]
}