{
 "title": "Firedancer Networking",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(quic_connections_active,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QUIC packets",
   "type": "timeseries",
   "description": "UDP packet rate handled by all QUIC tiles.\nPositive numbers indicate incoming packets (RX), negative numbers indicate outgoing packets (TX)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(quic_received_packets{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "RX pps"
    },
    {
     "expr": "-sum(rate(quic_sent_packets{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TX pps"
    }
   ]
  },
  {
   "title": "QUIC bandwidth",
   "type": "timeseries",
   "description": "UDP line rate received and sent by all QUIC tiles. \nThis includes network headers (Ethernet, IPv4, UDP header, QUIC header, QUIC payload)",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(quic_received_bytes{instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "RX bitrate"
    },
    {
     "expr": "-sum(rate(quic_sent_bytes{instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "TX bitrate"
    }
   ]
  },
  {
   "title": "QUIC Txns Recvd",
   "type": "stat",
   "description": "Transaction count received in the current interval",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_txns_received{instance=~\"$instance\",tpu_recv_type=\"quic_fast\"}[$__range])) + sum(increase(quic_txns_received{instance=~\"$instance\",tpu_recv_type=\"quic_frag\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUIC Txns Failed",
   "type": "stat",
   "description": "Transaction count failed in QUIC stream handling code (abandoned, too large, overrun). Not counting small streams",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_txns_abandoned{instance=~\"$instance\"}[$__range])) + sum(increase(quic_quic_txn_too_large{instance=~\"$instance\"}[$__range])) + sum(increase(quic_txns_overrun{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Complete Rate",
   "type": "gauge",
   "description": "Ratio of streams received vs streams started",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(quic_txns_received{instance=~\"$instance\",tpu_recv_type=\"quic_fast\"}[$__range])) + sum(increase(quic_txns_received{instance=~\"$instance\",tpu_recv_type=\"quic_frag\"}[$__range]))) / (sum(increase(quic_txns_received{instance=~\"$instance\",tpu_recv_type=\"quic_fast\"}[$__range])) + sum(increase(quic_txn_reasms_started{instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUIC conns",
   "type": "timeseries",
   "description": "Sum of QUIC connection counts across all QUIC tiles",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conns" } },
   "targets": [
    {
     "expr": "sum(quic_connections_active{instance=~\"$instance\"})",
     "legendFormat": "Conns"
    }
   ]
  },
  {
   "title": "QUIC Conns Created",
   "type": "stat",
   "description": "Cumulative number of connections created in the current Grafana time range",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_connections_created{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Frames",
   "type": "timeseries",
   "description": "Number of frames per second for each QUIC frame type.\n\n'stream' frames carry Solana transactions. \n'ping' frames do keep-alive to avoid connection timeouts.\nEverything else is metadata.\n\nUse shift+left click to hide certain frame types.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (quic_frame_type) (rate(quic_received_frames{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{quic_frame_type}}"
    }
   ]
  },
  {
   "title": "QUIC Conns Aborted",
   "type": "stat",
   "description": "Cumulative number of connections killed by QUIC tiles, in the current Grafana time range.\n\nTypical reasons include:\n- TLS handshake failure\n- Internal allocation failure\n\nDoes not include timeouts",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_connections_aborted{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUIC Conns Gracef. Closed",
   "type": "stat",
   "description": "Cumulative number of connections gracefully closed. AKA normal client disconnects.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_connections_closed{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPU Transaction Rate",
   "type": "timeseries",
   "description": "QUIC stream events per second\n(Each QUIC stream corresponds to one Solana transaction)\n\n- QUIC Unfragmented Rcvd: Peer sent an entire transaction in one QUIC frame\n- QUIC Fragmented Rcvd: Peer sent a transaction fragment\n- QUIC Abandoned: Txn dropped because the connection closed\n- QUIC Overrun: Reassembly operation dropped because lack of buffer space\n- QUIC Txn Undersz: Stream fully received but it's smaller than the smallest valid transaction. Some clients abuse undersize streams as a ping mechanism but this is harmless to Firedancer\n- QUIC Txn Oversz: Stream byte received that is beyond the transaction MTU\n- UDP Rcvd: Peer sent an entire transaction in one UDP packet\n- UDP Undersz: UDP packet too small\n- UDP Oversz: UDP packet too large",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (tpu_recv_type) (rate(quic_txns_received{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Rcvd {{tpu_recv_type}}"
    },
    {
     "expr": "sum(rate(quic_txns_abandoned{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Abandoned"
    },
    {
     "expr": "sum(rate(quic_txns_overrun{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Overrun"
    },
    {
     "expr": "sum(rate(quic_quic_txn_too_small{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Txn Undersz"
    },
    {
     "expr": "sum(rate(quic_quic_txn_too_large{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Txn Oversz"
    },
    {
     "expr": "sum(rate(quic_non_quic_packet_too_small{instance=~\"instance\"}[$__rate_interval]))",
     "legendFormat": "UDP Undersz"
    },
    {
     "expr": "sum(rate(quic_non_quic_packet_too_large{instance=~\"instance\"}[$__rate_interval]))",
     "legendFormat": "UDP Oversz"
    }
   ]
  },
  {
   "title": "QUIC Handshake Pool",
   "type": "timeseries",
   "description": "Handshake events per second\n\n- Alloc Fail: Handshake object pool is full (indicates connection attempt spam) \n- Created: Handshake object allocated",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(quic_handshake_error_alloc_fail{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Alloc Fail"
    },
    {
     "expr": "sum(rate(quic_handshakes_created{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "QUIC Conn Rejects",
   "type": "timeseries",
   "description": "Connections rejected per second\n\n- Alloc Fail: Aborted because the connection table was full\n- TLS Fail: Aborted because the TLS 1.3 handshake failed\n- Retry Fail: Client send an expired or invalid retry token (QUIC Retry are comparable to TCP SYN cookies)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(quic_connection_error_no_slots{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Alloc Fail"
    },
    {
     "expr": "sum(rate(quic_connection_error_tls_fail{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TLS Fail"
    },
    {
     "expr": "sum(rate(quic_connection_error_retry_fail{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Retry Fail"
    }
   ]
  },
  {
   "title": "QUIC Conn Churn",
   "type": "timeseries",
   "description": "Connection events per second.\n\n- Created: Connection objects created (tracked before the handshake succeeds)\n- Aborted: Connections killed by the validator\n- Graceful Closed: Connections gracefully closed by the peer\n- Timeout: Connections garbage-collected by the validator because no data was seen for the duration of the idle timeout",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(quic_connections_created{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(rate(quic_connections_aborted{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(rate(quic_connections_closed{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Graceful Closed"
    },
    {
     "expr": "sum(rate(quic_connections_timed_out{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "QUIC RX Drops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 26 },
   "targets": [
    {
     "expr": "increase(link_overrun_polling_frag_count{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval])",
     "legendFormat": "QUIC drops"
    },
    {
     "expr": "sum(increase(tile_context_switch_involuntary_count{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]))",
     "legendFormat": "Involuntary Context Switches"
    },
    {
     "expr": "sum(increase(quic_frame_fail_parse{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]))",
     "legendFormat": "QUIC Parse Fail"
    },
    {
     "expr": "sum by (quic_enc_level) (increase(quic_pkt_crypto_failed{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval])) != 0",
     "legendFormat": "QUIC Crypto Fail (({{quic_enc_level}}))"
    },
    {
     "expr": "sum by (quic_enc_level) (increase(quic_pkt_no_key{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval])) != 0",
     "legendFormat": "QUIC No Key ({{quic_enc_level}})"
    }
   ]
  },
  {
   "title": "QUIC RX Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(quic_receive_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(quic_receive_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(quic_receive_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(quic_receive_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (increase(quic_receive_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "QUIC ACK TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (quic_ack_tx) (rate(quic_ack_tx{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{quic_ack_tx}}"
    }
   ]
  },
  {
   "title": "Frame Dups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(quic_frags_dup{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]))",
     "legendFormat": "Duplicate Frags"
    }
   ]
  },
  { "title": "Net Tile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Non-QUIC packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(net_received_packets{instance=~\"$instance\"}[$__rate_interval])) - sum(rate(quic_received_packets{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "RX pps"
    },
    {
     "expr": "-sum(rate(net_sent_packets{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(quic_sent_packets{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TX pps"
    }
   ]
  },
  {
   "title": "Non-QUIC bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(sum(rate(net_received_bytes{instance=~\"$instance\"}[$__rate_interval])) - sum(rate(quic_received_bytes{instance=~\"$instance\"}[$__rate_interval])))*8",
     "legendFormat": "RX bitrate"
    },
    {
     "expr": "-sum(rate(net_sent_bytes{instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "TX bitrate"
    }
   ]
  },
  {
   "title": "Dropped Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(net_xdp_rx_dropped_other{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(net_xdp_rx_dropped_ring_full{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "RX"
    },
    {
     "expr": "-sum(rate(net_tx_dropped{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "stat",
   "description": "Number of packets dropped in the current Grafana time interval",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(net_xdp_rx_dropped_other{instance=~\"$instance\"}[$__range]) + increase(net_xdp_rx_dropped_ring_full{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(increase(net_tx_dropped{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}