---
bootstrap_user: devops
container_name_alertmanager: alertmanager
alertmanager_web_port: 9093
alertmanager_config_dir: '{{ home_dir }}/alertmanager'
home_dir_default: /home/{{ bootstrap_user }}
home_dir: '{{ home_dir_custom | default(home_dir_default) }}'
alertmanager_config_file: alertmanager.yml
alertmanager_public_port: 39093
