---
- name: Update and upgrade all available packages
  when: upgrade_all_packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install common packages
  ansible.builtin.apt:
    # git: To clone repos
    # nano: To quickly edit files
    # htop: To quickly visualize resource usage
    # gnupg: For docker's copy key step
    # build-essential: To build Lodestar dependencies (i.e. bcrypto)
    # python3: For docker's using ansible_python_interpreter: /usr/bin/python3
    name: [git, nano, htop, gnupg, build-essential, python3, apache2-utils]
    state: latest
    update_cache: true
