---
##### docker task vars #####
# Otherwise sudo will be required to do any docker action
docker_users:
  - "{{bootstrap_user}}"

docker_daily_prune: true

#### other vars ####
upgrade_all_packages: false
