---
    - name: Create directory for node store on host machine
      file:
        path: "{{ ansible_env.HOME }}/my-node-store"
        state: directory
    - name: Set Docker environment variables
      set_fact:
        docker_env_vars:
          NODE_TYPE: "{{ NODE_TYPE }}"
          P2P_NETWORK: "{{ P2P_NETWORK }}"
          RPC_URL: "{{ RPC_URL }}"
    - name: Initialize Celestia node store
      community.docker.docker_container:
        name: celestia_init
        image: ghcr.io/celestiaorg/celestia-node:v0.14.0
        command: "celestia {{ NODE_TYPE }} init "
        user: "0:0"
        env:
          NODE_TYPE: "{{ NODE_TYPE }}"
          P2P_NETWORK: "{{ NETWORK }}"
          HOME: "/devops"
        volumes:
          - "{{ ansible_env.HOME }}/my-node-store:/home/celestia"
        state: started
        auto_remove: true
      environment:
        HOME: /devops

    - name: Start Celestia light node
      docker_container:
        name: celestia_light
        image: ghcr.io/celestiaorg/celestia-node:v0.14.0
        user: "0:0"
        env:
          NODE_TYPE: "{{ docker_env_vars.NODE_TYPE }}"
          P2P_NETWORK: "{{ docker_env_vars.P2P_NETWORK }}"
          RPC_URL: "{{ docker_env_vars.RPC_URL }}"
        volumes:
          - "{{ ansible_env.HOME }}/my-node-store:/home/celestia"
        command: "celestia {{ docker_env_vars.NODE_TYPE }} start --core.ip {{ docker_env_vars.RPC_URL }} --p2p.network {{ docker_env_vars.P2P_NETWORK }}"
        state: started
      environment:
        HOME: /devops