---
prometheus:
  web_port: 9090
  datasource_uid: prometheus

metrics_auth:
  user: '{{ metrics_auth_user }}'
  password: '{{ prometheus_auth_password }}'

grafana_container_name: grafana
grafana_container_image_and_tag: grafana/grafana:10.1.1
