- name: Create NGINX configuration directory
  ansible.builtin.file:
    path: "{{ nginx_config_dir }}"
    state: directory

- name: Template NGINX config file
  ansible.builtin.template:
    src: "templates/nginx.conf.j2"
    dest: "{{ nginx_config_dir }}/nginx.conf"

- name: Create Basic Auth file
  ansible.builtin.command:
    cmd: "htpasswd -bc {{ nginx_config_dir }}/metrics.htpasswd {{ vault_nodeexporter_basic_auth_user }} {{ vault_nodeexporter_basic_auth_password }}"
