---
- name: Remove NGINX container if exists
  community.docker.docker_container:
    name: "{{ nginx_container_name }}"
    state: absent
  ignore_errors: true

- name: Start NGINX container
  community.docker.docker_container:
    name: "{{ nginx_container_name }}"
    state: started
    image: "{{ nginx_image_and_tag }}"
    pull: true
    volumes: "{{ nginx_volumes }}"
    restart_policy: always
    network_mode: host
    log_driver: json-file
    log_options:
      max-file: '10'
      max-size: 30m
      mode: non-blocking
      max-buffer-size: 4m
