---
- name: Ensure allowing SSH (port 22)
  ansible.builtin.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Block all app-specific ports
  ansible.builtin.ufw:
    rule: deny
    port: "{{ item.value.port }}"
    proto: any
  loop: "{{ metrics_apps | dict2items }}"
  when: item.value.port is defined

- name: Allow public_ports of apps
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item.value.public_port }}"
    proto: tcp
  with_items: "{{ metrics_apps | dict2items }}"

- name: Ensure UFW is enabled
  ansible.builtin.ufw:
    state: enabled

- name: Reload UFW to apply rules
  ansible.builtin.ufw:
    state: reloaded
