---
- name: copy identity key
  copy:
    src: files/validator-keypair.json
    dest: /home/devops/solana-validator/config/validator-keypair.json
  become: no

- name: copy vote key
  copy:
    src: files/vote-account-keypair.json
    dest: /home/devops/solana-validator/config/vote-account-keypair.json
  become: no

- name: copy validator start up script
  copy:
    src: files/validator.sh
    dest: /home/devops/solana-validator/config/validator.sh
    owner: "{{ non_root_user }}"
    group: "{{ non_root_group }}"
    mode: "0755"
  become: no

- name: Copy 'solana-exporter' docker compose file
  template:
    src: templates/exporter.docker-compose.yml.j2
    dest: /home/devops/solana-exporter/exporter.docker-compose.yml