---
# Default endpoint URL is 'mainnet-beta'. Ensuring correct endpoint is set
- name: set solana config to use keypair
  shell: solana config set --url {{ solana_api_url }}
  become: no

- name: set solana config to use keypair
  shell: solana config set --keypair {{ solana_validator_dir }}/config/validator-keypair.json
  become: no

- name: enable solana validator service
  shell: systemctl enable solana.service
  become: yes

- name: start solana validator service
  shell: systemctl start solana.service
  become: yes

- name: Stop 'solana-exporter' container if already existing
  shell:
    "docker-compose -f {{ solana_exporter_dir }}/exporter.docker-compose.yml down"
  ignore_errors: yes

- name: Start solana-exporter container
  shell:
    "docker-compose -f {{ solana_exporter_dir }}/exporter.docker-compose.yml up -d"
