---
solana_version: "v2.1.13"
solana_api_url: "https://api.{{ network_type }}.solana.com/"

solana_validator_dir: /home/devops/solana-validator
solana_exporter_dir: /home/devops/solana-exporter
# Ports range not managed by firewall yet
solana_port_range: "8000:8020"

solana_exporter_container_name: "solana_exporter"
solana_exporter_container_image_and_tag: "mcamou/solana-exporter:b8fcc7c170049d5c9c34ea57b9f2fcb3a0b5044d"
vote_account_pubkey: 
node_key: 

non_root_user: "devops"
non_root_group: "devops"

solana_binary_path: /bin:/usr/bin:/home/devops/.local/share/solana/install/active_release/bin

