---
container_names:
  prometheus: prometheus

metrics_auth:
  user: '{{ metrics_basic_auth_user }}'
  password: '{{ metrics_basic_auth_password }}'

ports:
  prometheus_web: 9090
  prometheus_public: 39090
  metrics_node_exporter_local: 9100
  metrics_node_exporter_public: 39100

directories:
  home_default: /home/devops
  home: '{{ home_dir_custom | default(directories.home_default) }}'
  prometheus_config: '{{ directories.home }}/prometheus'
  prometheus_target: '{{ directories.prometheus_config }}/targets'

container_dirs:
  prometheus_config: /etc/prometheus

alertmanager:
  web_port: 9093
  url: 127.0.0.1:{{ alertmanager.web_port }}
