---
- name: Deploy Celestia Light Node
  hosts: all  
  become: true 

  roles:
    - role : celestia
      vars:
        NETWORK: mocha
        NODE_TYPE: light
        P2P_NETWORK: mocha
        RPC_URL: public-celestia-mocha4-consensus.numia.xyz
