# Rules and alerts are read from the specified file(s)
rule_files:
  - "{{ prometheus_config_container_dir }}/rules.yml"

scrape_configs:
  - job_name: "metrics"

    # Respect the labels from the targets, override whatever they say
    honor_labels: true

    # From: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
    basic_auth:
      username: "{{ metrics_auth_user }}"
      password: "{{ metrics_auth_password }}"

    # Scrape every 2 slots on average. Use long timeout, to get metrics from overloaded nodes
    scrape_interval: 24s
    # scrape_timeout must be <= scrape_interval
    scrape_timeout: 24s

    # IPs of the target nodes are created with a loop template
    file_sd_configs:
      - files:
          - "{{ prometheus_config_container_dir }}/targets/*.yml"
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["{{ alertmanager_url }}"]
