groups:

  - name: AllInstances
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Instance {{ $labels.instance }} down
          description: |
            {{ $labels.instance }} of scraper {{ $labels.scrape_location }} has been down for +5 minutes.

      - alert: PrometheusRuleEvaluationFailures
        expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Prometheus rule evaluation failures (instance {{ $labels.instance }})
          description: "Prometheus encountered {{ $value }} rule evaluation failures, leading to potentially ignored alerts.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host out of memory (instance {{ $labels.instance }})
          description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostSwapIsFillingUp
        expr: node_memory_SwapTotal_bytes > 0 and (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host swap is filling up (instance {{ $labels.instance }})
          description: Swap is filling up (>80%)\n  VALUE = {{ $value }}

      - alert: HostDiskWillFillIn24Hours
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host disk will fill in 24 hours (instance {{ $labels.instance }})
          description: "Filesystem is predicted to run out of space within the next 24 hours at current write rate\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes <= 20 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: Disk is almost full (≤ 20% left)\n  VALUE = {{ $value }}

      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: CPU load is > 90%\n  VALUE = {{ $value }}

      - alert: HostPhysicalComponentTooHot
        expr: node_hwmon_temp_celsius > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host physical component too hot (instance {{ $labels.instance }})
          description: Physical hardware component too hot\n  VALUE = {{ $value }}

      - alert: HostOOMKillDetected
        expr: increase(node_vmstat_oom_kill[1m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host OOM kill detected (instance {{ $labels.instance }})
          description: "OOM kill detected\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostClockNotSynchronising
        expr: min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host clock not synchronising (instance {{ $labels.instance }})
          description: "Clock not synchronising. Ensure NTP is configured on this host.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostRequiresReboot
        expr: node_reboot_required > 0
        for: 4h
        labels:
          severity: info
        annotations:
          summary: Host requires reboot (instance {{ $labels.instance }})
          description: "{{ $labels.instance }} requires a reboot.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      #  deriv instead of rate because rate only works on counters
      - alert: SystemMemoryLeakDetected
        expr: deriv(node_memory_MemAvailable_bytes{group="unstable"}[4h])/(1024^3) < -0.5
        for: 1d
        labels:
          severity: warning
        annotations:
          summary: 'Potential server memory leak detected'
          description: "The heap size has been increasing over the past 15 minutes, indicating a potential memory leak on {{ $labels.instance }}.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: NginxHighHttp5xxErrorRate
        expr: sum(rate(nginx_http_requests_total{status=~"^5.."}[1m])) / sum(rate(nginx_http_requests_total[1m])) * 100 > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Nginx high HTTP 5xx error rate (instance {{ $labels.instance }})
          description: "Too many HTTP requests with status 5xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    ################
    #### SOLANA ####
    ################
  - name: SolanaValidatorAlerts
    rules:
      # Alert for increased stake
      - alert: SolanaFireDancerActiveStakeAmountIncreased
        expr: delta(solana_validator_activated_stake[10m]) / 1000000000 > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Fire Dancer validator - Active Stake amount has increased by {{ $value }} for {{ $labels.job }} instance {{ $labels.instance }}"
          description: "Stake amount has increased in the last 10 minutes."

      # Alert for decreased stake
      - alert: SolanaFireDancerActiveStakeAmountDecreased
        expr: delta(solana_validator_activated_stake[10m]) / 1000000000 < 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Fire Dancer validator - Active Stake amount has decreased by {{ $value }} for {{ $labels.job }} instance {{ $labels.instance }}"
          description: "Stake amount has decreased in the last 10 minutes."

      - alert: AgaveValidatorLastVote
        expr: round(solana_cluster_last_vote{job="solana"} - on(node, instance, network) solana_validator_last_vote{job="solana"}, 2) > 100
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Agave Validator last vote compared to Cluster last vote (instance {{ $labels.instance }})"
          description: "The difference between the validator's last vote and the cluster's last vote is greater than 100.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Agave Validator Fee Payer Balance (Identity)
        expr: solana_account_balance{job="solana", network="testnet", node="validator-01", address="EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99"} < 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Agave Validator fee payer balance (identity) (instance {{ $labels.instance }})"
          description: "The fee payer balance for the validator is less than 1.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Firedancer Validator Blockheight Progress
        expr: rate(solana_node_block_height{job="solana", network="testnet", node="validator-01"}[5m]) < 0.5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Firedancer Validator blockheight progress (instance {{ $labels.instance }})"
          description: "The blockheight progress rate for the validator is less than 0.5.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Agave Validator Is Delinquent
        expr: solana_validator_delinquent{job="solana", network="testnet", node="validator-01"} > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Agave Validator is delinquent (instance {{ $labels.instance }})"
          description: "The validator is delinquent.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Agave Validator Active Stake Amount
        expr: solana_validator_active_stake{job="solana", network="testnet", node="validator-01"} < 10000
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Agave Validator active stake amount (instance {{ $labels.instance }})"
          description: "The active stake amount for the validator is less than 10000.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Firedancer Validator Last Vote Progress
        expr: increase(solana_validator_last_vote{job="solana", network="testnet", node="validator-01"}[10m]) < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Firedancer Validator last vote progress (instance {{ $labels.instance }})"
          description: "The last vote progress for the validator is less than 10.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Firedancer Validator Is Active
        expr: sum(solana_active_validators{job="solana", state=~"current|delinquent"}) by (instance) == 0
        for: 5m
        labels:
            severity: critical
        annotations:
            summary: "Firedancer Validator is not active (instance {{ $labels.instance }})"
            description: "The validator is not active or has an unexpected state.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Firedancer Validator Is Delinquent (Should Not Be)
        expr: solana_validator_delinquent{job="solana"} > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Firedancer Validator is delinquent (should not be) (instance {{ $labels.instance }})"
          description: "The validator is delinquent but should not be.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Firedancer Validator Has Skipped Blocks
        expr: increase(solana_leader_slots_total{nodekey="EfeFqTrp6LMYGmL9KKMSTKg9Xtjxn8AJTcjTCaY7bo99",status="skipped"}[10m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Firedancer Validator has skipped blocks (instance {{ $labels.instance }})"
          description: "The validator has skipped blocks.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    ################
    #### NAMADA ####
    ################

  - name: NamadaValidatorAlerts
    rules:
      # Alert if validator state is different than "1 - Active"
      - alert: NamadaValidatorState
        expr: namada_validator_state{group="namada"} != 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Validator is not active on {{ $labels.instance }}"
          description: |
            "The validator with instance {{ $labels.instance }} is not active, it's state is : {{ $value }}.
            Possible states : 0 - unknown, 1 - active consensus set, 2 - active below capacity set, 3 - active below threshold set, 4 - jailed, 5 - inactive."

      # Alert if consensus height is not increasing
      - alert: NamadaLatestBlockNotIncreasing
        expr: increase(namada_node_latest_block{group="namada"}[5m]) == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Consensus height is not increasing on {{ $labels.instance }}"
          description: "The consensus height has not moved in the last 5 minutes for {{ $labels.instance }}. Current height: {{ $value }}."

      # Alert if uptime is low
      - alert: NamadaValidatorLowUpTime
        expr: (namada_validator_uptime_percentage{group="namada"}) <= 90
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "Low uptime on {{ $labels.instance }}"
          description: "The uptime has dropped to {{ $value }} or below, on {{ $labels.instance }}."

      # Alert of missed blocks
      - alert: NamadaMissedBlocksIncreasing
        expr: increase(namada_validator_missed_blocks{group="namada"}[10m]) >= 7
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Missed blocks in the last  {{ $labels.instance }}"
          description: "The validator has missed {{ $value }} blocks on {{ $labels.instance }}."

      # Alert if peer count is below or equal to 10
      - alert: NamadaValidatorLowPeers
        expr: (namada_tm_p2p_peers{group="namada"}) <= 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low peer count detected on {{ $labels.instance }}"
          description: "The number of peers has dropped to {{ $value }} or below, on {{ $labels.instance }}."

      # Alert if the node is not synced for long
      - alert: NamadaValidatorNotSynced
        expr: namada_node_catch_up{group="namada"} == 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Namada validator is not synced, has been trying to catch up for more than 30 minutes on {{ $labels.instance }}"
          description: "The validator is not synced for the last 30 minutes on {{ $labels.instance }}."

      # Alert if Rank changes significantly
      - alert: NamadaValidatorRank
        expr: (namada_validator_active_set_rank{group="namada"}) >= 150
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Namada validator Rank is {{ $value }} for the node {{ $labels.instance }}."
          description: |
            "Check the current value of {namada_network_active_set_size} and {namada_network_stake_threshold},
             to estimate if any action is needed to keep the validator in active set."

    ################
    #### COSMOS ####
    ################

  - name: FuelValidatorAlerts
    rules:
      # Alert if consensus height is not increasing
      - alert: FuelValidatorConsensusHeightNotIncreasing
        expr: increase(cometbft_consensus_height{group="fuel"}[5m]) == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Consensus height is not increasing on {{ $labels.instance }}"
          description: "The consensus height has not moved in the last 5 minutes for {{ $labels.instance }}. Current height: {{ $value }}."

      # Alert if peer count is below or equal to 10
      - alert: FuelValidatorLowPeers
        expr: (cometbft_p2p_peers{group="fuel"}) <= 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low peer count detected on {{ $labels.instance }}"
          description: "The number of peers has dropped to {{ $value }} or below on {{ $labels.instance }}."

      # Alert if number of transactions is zero
      - alert: FuelValidatorZeroTransactions
        expr: (cometbft_consensus_num_txs{group="fuel"}) == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "No transactions detected on {{ $labels.instance }}"
          description: "The number of transactions is zero on {{ $labels.instance }}."

      # Alert if the validator is jailed
      - alert: FuelValidatorJailed
        expr: cosmos_validator_jailed{group="fuel"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Validator is jailed on {{ $labels.instance }}"
          description: "The validator with instance {{ $labels.instance }} has been jailed."

      # Alert if the wallet balance drops below 50
      - alert: FuelWalletBalanceLow
        expr: cosmos_wallet_balance{group="fuel"} < 50
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Wallet balance is below 50 on {{ $labels.instance }}"
          description: "The wallet balance for {{ $labels.instance }} is less than 50."
